version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: wp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - network_divino
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  wordpress:
    image: wordpress:php8.2-fpm
    container_name: wp_app
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
    volumes:
      - ./src:/var/www/html
    networks:
      - network_divino

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - network_divino

  nginx:
    image: nginx:latest
    container_name: wp_nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    networks:
      - network_divino

volumes:
  db_data:

networks:
  network_divino:
